title: 7617 Code Standards
description: Code standards documentation for FRC team 7617.
theme: just-the-docs

url: https://CoffeeCoder1.github.io/7617-code-standards

# Aux links in the navbar
aux_links:
  "7617 GitHub":
    - "https://github.com/roboblazers7617"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# GitHub edit link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/CoffeeCoder1/7617-code-standards" # Repo URL
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
